version: "3.9"

services:
  app:
    build: .
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: admin
      DB_NAME: endur_indexerdb_test
      DATABASE_URL: postgresql://postgres:password@localhost:5432/endur_indexerdb_test
